month_dict <- data.frame(number = rep(1:12,3),
                         language = c(rep('en', 12), rep('es', 12), rep('ca', 12)), #rep(c('en', 'es', 'ca'), each = 3)),
                         month = 
                           c('January',
                             'February',
                             'March',
                             'April',
                             'May',
                             'June',
                             'July',
                             'August',
                             'September',
                             'October',
                             'November',
                             'December',
                             'Enero',
                             'Febrero',
                             'Marzo',
                             'Abril',
                             'Mayo',
                             'Junio',
                             'Julio',
                             'Agosto',
                             'Septiembre',
                             'Octubre',
                             'Noviembre',
                             'Diciembre',
                             'Gener',
                             'Febrer',
                             'Març',
                             'Abril',
                             'Maig',
                             'Juny',
                             'Juliol',
                             'Agost',
                             'Septembre',
                             'Octubre',
                             'Novembre',
                             'Desembre'),
                         stringsAsFactors = FALSE) %>%
  arrange(language, number)